### ISSUE TITLE
Maven build fails - Parent POM not resolvable

### ISSUE THREAD

**Issue by PeterWippermann** [mp911de/reactive-coding-workshop#1]
`./mvnw dependency:go-offline` fails because the Parent POM from Spring Boot can't be resolved.

I saw you added an additional repo for this SNAPSHOT dependency:
````xml
<repository>
	<id>spring-snapshots</id>
	<name>Spring Snapshots</name>
	<url>https://repo.spring.io/snapshot</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
````
Is there a known solution for this? Or should I try to temporarly add this repo to my `settings.xml` to get this running?

**Comment by mp911de** [comment]
I added `spring-snapshots` because Spring snapshot builds are deployed to repo.spring.io and available through `https://repo.spring.io/snapshot`.  Please make sure your `.m2/settings.xml` does not declare proxy (mirror) for all repos. Removing `settings.xml` temporarily might be the better approach.

**Comment by PeterWippermann** [comment]
There is a command-line argument to override the Maven settings. I wanted to provide no file, but Maven complained, so I (mis-)used your POM ;-)

`./mvnw dependency:go-offline -U --settings pom.xml --global-settings pom.xml`

After 7 minutes of downloading the build finished successfully!
So thanks for your help and I'm looking forward to your workshop! :-)

**Comment by PeterWippermann** [comment]
By the way, I just realised there will be no Wifi at the conference venue! :-(
I hope your audience follows your advice to go-offline in advance.

**Comment by mp911de** [comment]
Download takes quite a while...thanks for your feedback.
